---
title: "Combine All Prey Density Data"
author: "Maddee Rubenson (FlowWest)"
date: "`r Sys.Date()`"
output:
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE, 
                      message = FALSE)

library(tidyverse)
library(lubridate)
library(knitr)
library(readxl)
library(sf)
library(preyDataProcessing)

options(scipen=999)
```

## Combine Prey Density Data 

```{r}

all_prey <- bind_rows(
  preyDataProcessing::cordoleani_prey_data,
  preyDataProcessing::zeug_merced_prey_data, 
  preyDataProcessing::zeug_sanJoaquin_prey_data, 
  preyDataProcessing::montgomery_prey_data, 
  preyDataProcessing::guignard_prey_data, 
  preyDataProcessing::corline_prey_data,
  preyDataProcessing::zooper_prey_data
) |> 
  filter(!is.na(habitat_type)) |> 
  filter(!is.na(date))

```

### Exploratory Analysis of Prey Density Data 

```{r}
ggplot(all_prey, aes(x = as.factor(month(date)), y = prey_density)) + 
  geom_point() + 
  facet_wrap(~habitat_type) + 
  xlab('month') +
  ylab('prey density (count/L)') + 
  ggtitle('Distrubtion of prey density across years and habitat types', 
          subtitle = "Aggregated data across all authors") 


ggplot() +
  geom_boxplot(data = all_prey, aes(x = author, y = prey_density)) +
  scale_y_continuous(trans='log10') + 
  ylab('log10 prey_density') + 
  coord_flip()
```

```{r}

all_prey %>%
  group_by(habitat_type, author) %>%
  select(prey_density) %>%
  summarise_if(is.numeric, .funs = c("mean", "min", "max", "var"), na.rm = TRUE) %>% 
  kable(digits=1, format.args = list(big.mark = ","))

```
